### ISSUE TITLE
Missing redirect from http:// to https://

### ISSUE THREAD

**Issue by NetWin** [snapADDY/snapaddy-mapping-doc#1]
if i go to http://mapping.snapaddy.com i dont get redirected to https://mapping.snapaddy.com

Chrome shows a "Nicht sicher" Notification next to the url if the website is not served via https
![image](https://user-images.githubusercontent.com/7582077/44325504-46b34b00-a459-11e8-9e14-7b7b6f849ceb.png)

**Comment by rnarian** [comment]
![image](https://user-images.githubusercontent.com/1174951/44325650-ab6ea580-a459-11e8-8bff-1b6719fb5fa3.png)

I checked this box. Maybe that helps 🙏

**Comment by rnarian** [comment]
Seems to be working 👍
