### ISSUE TITLE
you cannot just paste JS code in a 1:1 mapping

### ISSUE THREAD

**Issue by NetWin** [snapADDY/snapaddy-mapping-doc#2]
this is not possible!
https://github.com/snapADDY/snapaddy-mapping-doc/blame/master/_posts/2018-07-05-mappings.md#L36-L48

but its possible to do it like this:
```
{
      "mappings": {
            "lead": {
                    "Salutation": "{{ gender == 0? 'Herr' : (gender == 1? 'Frau' : '') }}"
            },
            "contact": {},
            "account": {}
        }
}
```

every mapped expression needs to be inside of a curly bracket block `{{ <expression> }}`

**Comment by SlicSide** [comment]
Fixed by bceef31c7d3fbac0b83224c3fef425b621118bb6
