### ISSUE TITLE
Remove most Special Fields for CRM

### ISSUE THREAD

**Issue by NetWin** [snapADDY/snapaddy-mapping-doc#3]
from here: https://mapping.snapaddy.com/variables-grabber

**All** id fields are obsolete and dont work for the Export2.0 anymore! They were replaced by the workflow.dependsOn property (https://mapping.snapaddy.com/workflows)

----

### These are the only necessary properties:

- Salesforce: 
	- userId : id of the currently logged in user

- SugarCRM: 
	- userId :  id of the currently logged in user
	- salutation : default sugarcrm salutation, based of snapaddy.gender and snapaddy.title

---- 

properties like `topic` or `deal_title` are just aliases for `{{ organization }}` and should not be used anymore (even though there are still available)

**Comment by SlicSide** [comment]
@NetWin I deleted all the id properties and changed the aliases to {{organization}}. Is there something I need to add for this Salesforce and SugarCRM stuff?
