### ISSUE TITLE
wrong link in https://mapping.snapaddy.com/mappings

### ISSUE THREAD

**Issue by julia96b** [snapADDY/snapaddy-mapping-doc#40]
![image](https://user-images.githubusercontent.com/117269934/205642302-d15bbba3-efc5-44bf-ab93-282441604b79.png)
![image](https://user-images.githubusercontent.com/117269934/205642345-6df461db-8cbc-4e58-9ecc-598b236e4eaa.png)

Link(https://mapping.snapaddy.com/variables-visitreport) for commands on page https://mapping.snapaddy.com/mappings leads to ERROR!

**Comment by rebekkaB25** [comment]
still rotted link to mapping samples on https://portal.snapaddy.com/de/knowledge/kann-ich-mein-crm-mapping-selbst-erstellen-und-anpassen-snapaddy-dataquality
